### ISSUE TITLE
Doc : add `use-throttled-hook` text in readme file

### ISSUE THREAD

**Issue by Ashish-simpleCoder** [Ashish-simpleCoder/classic-react-hooks#55]
- Add `use-throttled-hook` text after `use-debounced-fn` text in readme file.

**Comment by Mounayer** [comment]
Hello @Ashish-simpleCoder! Please assign this to me, I'll get it done asap and pop the pr as soon as hacktoberfest starts!

Just to be clear, this is simply adding the `use-throttled-hook` into the `README.md` file, right after `use-debounced-fn`, correct?

**Comment by Ashish-simpleCoder** [comment]
> Hello @Ashish-simpleCoder! Please assign this to me, I'll get it done asap and pop the pr as soon as hacktoberfest starts!
> 
> Just to be clear, this is simply adding the `use-throttled-hook` into the `README.md` file, right after `use-debounced-fn`, correct?

Yaa, you can take it.

**Comment by Ashish-simpleCoder** [comment]
Looks great. Thanks for contributing.
