### ISSUE TITLE
Text is not visible in light-theme for useSyncedEffect hook's doc

### ISSUE THREAD

**Issue by Ashish-simpleCoder** [Ashish-simpleCoder/classic-react-hooks#6]
**Describe the bug**
- In light theme, text is not visible for useSyncedEffect hook's doc

**Expected behavior**
- Background should change according to theme.

**Screenshots**
![image](https://github.com/Ashish-simpleCoder/classic-react-hooks/assets/62009244/d92ef502-0a79-4cd9-8f36-21518ede0daf)

**How to fix**
- Go to src/hooks/use-synced-effect/example.tsx to fix the issue.

**Comment by ChaudaryHammad** [comment]
i can solve it assign it to me

**Comment by Ryan-Biondo** [comment]
I've identified a potential cause of the background color issue in light mode. The div lacks a dark: variant for the background color, so I propose to change the line to <div className="bg-gray-800 dark:bg-gray-200 px-2" ref={logRef}></div>
